ALTER TABLE reports ENGINE=InnoDB;
ALTER TABLE reports_spy ENGINE=InnoDB;
ALTER TABLE reports_other ENGINE=InnoDB;
ALTER TABLE reports_market ENGINE=InnoDB;
ALTER TABLE reports_battle ENGINE=InnoDB;

ALTER TABLE reports MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

DELETE FROM reports_spy WHERE id NOT IN (SELECT id FROM reports);
DELETE FROM reports_other WHERE id NOT IN (SELECT id FROM reports);
DELETE FROM reports_market WHERE id NOT IN (SELECT id FROM reports);
DELETE FROM reports_battle WHERE id NOT IN (SELECT id FROM reports);
ALTER TABLE reports_spy ADD CONSTRAINT FK_REPORTS_SPY FOREIGN KEY (`id`) REFERENCES reports (`id`) ON DELETE CASCADE;
ALTER TABLE reports_other ADD CONSTRAINT FK_REPORTS_OTHER FOREIGN KEY (id) REFERENCES reports (id) ON DELETE CASCADE;
ALTER TABLE reports_market ADD CONSTRAINT FK_REPORTS_MARKET FOREIGN KEY (id) REFERENCES reports (id) ON DELETE CASCADE;
ALTER TABLE reports_battle ADD CONSTRAINT FK_REPORTS_BATTLE FOREIGN KEY (id) REFERENCES reports (id) ON DELETE CASCADE;
