# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        default:
            versionCheck: false
            toolbar: "standard"
    toolbars:
        items:
            standard.insert: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley' ]

