security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        legacy: { id: EtoA\Security\LegacyPasswordHasher }
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            migrate_from:
                - legacy

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        admin: { id: EtoA\Security\Admin\AdminUserProvider }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: admin
            custom_authenticators:
                - EtoA\Security\Admin\AdminAuthenticator
            entry_point: EtoA\Security\Admin\AdminAuthenticator
            logout:
                path: /admin/logout
                target: /admin/
            two_factor:
                auth_form_path: admin_2fa_login
                check_path: admin_2fa_login_check

        main:
            lazy: true
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        # allow unauthenticated admin users to access the login form
        - { path: ^/admin/login/tfa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        # but require authentication for all other admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_ADMIN_MASTER: [ROLE_ADMIN_SUPER-ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN]
        ROLE_ADMIN_SUPER-ADMIN: ROLE_ADMIN_TRIAL-ADMIN
        ROLE_ADMIN_TRIAL-ADMIN: ROLE_ADMIN
        ROLE_ADMIN_CHAT-ADMIN: ROLE_ADMIN
