twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'form_table_layout.html.twig' ]
  globals:
    resourceNames: '@EtoA\Universe\Resources\ResourceNames'

when@test:
  twig:
    strict_variables: true
