Library(target="anyoption", source=Split("src/lib/anyoption/anyoption.cpp")) 
Program(target="etoad", LIBS=["anyoption"], LIBPATH=".", source=Split("src/main.cpp src/lib/logger.cpp src/lib/pidfile.cpp"))

