ALTER TABLE `reports_other` CHANGE `res_0` `res_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_1` `res_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_2` `res_2` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_3` `res_3` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_4` `res_4` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_5` `res_5` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `reports_spy` CHANGE `res_0` `res_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_1` `res_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_2` `res_2` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_3` `res_3` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_4` `res_4` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_5` `res_5` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `reports_market` CHANGE `sell_0` `sell_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `sell_1` `sell_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `sell_2` `sell_2` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `sell_3` `sell_3` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `sell_4` `sell_4` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `sell_5` `sell_5` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_0` `buy_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_1` `buy_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_2` `buy_2` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_3` `buy_3` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_4` `buy_4` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `buy_5` `buy_5` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `reports_battle` CHANGE `res_0` `res_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_1` `res_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_2` `res_2` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_3` `res_3` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_4` `res_4` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `res_5` `res_5` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `wf_0` `wf_0` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `wf_1` `wf_1` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `wf_2` `wf_2` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `logs_battle` CHANGE `win_metal` `win_metal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_crystal` `win_crystal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_pvc` `win_pvc` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_tritium` `win_tritium` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_food` `win_food` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_metal` `tf_metal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_crystal` `tf_crystal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_pvc` `tf_pvc` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `logs_battle_queue` CHANGE `win_metal` `win_metal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_crystal` `win_crystal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_pvc` `win_pvc` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_tritium` `win_tritium` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `win_food` `win_food` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_metal` `tf_metal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_crystal` `tf_crystal` BIGINT UNSIGNED NOT NULL DEFAULT '0',
CHANGE `tf_pvc` `tf_pvc` BIGINT UNSIGNED NOT NULL DEFAULT '0';