<?php declare(strict_types=1);

namespace EtoA\Security\Player;

use EtoA\User\UserSittingRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\PasswordUpgradeBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface;

/**
 * Accepts the login submitted by the portal's (etoa-web) embedded login
 * widget, which posts credentials under field names derived from a
 * per-request token instead of fixed names - the same contract the old
 * htdocs game used. Keeping that contract means the portal's `rounds.round_url`
 * for this round can point here without any change on the portal side.
 *
 * Token layout, as generated by etoa-web's FrontendController::getGameLogin():
 *   token = sha1(ip . userAgent . t) . dechex(t)
 *   nick field name     = sha1('nick' . token . t)
 *   password field name = sha1('password' . token . t)
 */
class ExternalPlayerAuthenticator extends AbstractAuthenticator implements AuthenticationEntryPointInterface
{
    use PlayerCredentialsUserBadgeTrait;

    // generous enough to cover filling in the form, tight enough to keep the token single-use in practice
    private const TOKEN_MAX_AGE = 300;

    public function __construct(
        private readonly PlayerUserProvider                 $userProvider,
        private readonly PlayerAuthenticationSuccessHandler $authenticationSuccessHandler,
        private readonly PlayerAuthenticationFailureHandler $authenticationFailureHandler,
        private readonly UrlGeneratorInterface              $urlGenerator,
        private readonly UserSittingRepository              $sittingRepository
    ) {
    }

    public function supports(Request $request): bool
    {
        return $request->isMethod('POST')
            && $request->attributes->get('_route') === 'game.login.external';
    }

    public function authenticate(Request $request): Passport
    {
        [$username, $password] = $this->getCredentials($request);

        return new Passport(
            $this->createPlayerUserBadge($username, $password),
            new PasswordCredentials($password),
            [
                new PasswordUpgradeBadge($password, $this->userProvider),
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return $this->authenticationSuccessHandler->onAuthenticationSuccess($request, $token);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response
    {
        return $this->authenticationFailureHandler->onAuthenticationFailure($request, $exception);
    }

    /**
     * @return array{0: string, 1: string}
     */
    private function getCredentials(Request $request): array
    {
        $token = (string) $request->request->get('token');
        if (strlen($token) <= 40) {
            throw new BadCredentialsException('Invalid login token.');
        }

        $hash = substr($token, 0, 40);
        $timestamp = hexdec(substr($token, 40));

        if (abs(time() - $timestamp) > self::TOKEN_MAX_AGE) {
            throw new BadCredentialsException('Expired login token.');
        }

        $expected = sha1($request->getClientIp() . $request->headers->get('User-Agent') . $timestamp);
        if (!hash_equals($expected, $hash)) {
            throw new BadCredentialsException('Invalid login token.');
        }

        $nickField = sha1('nick' . $token . $timestamp);
        $passwordField = sha1('password' . $token . $timestamp);

        $username = trim((string) $request->request->get($nickField, ''));
        $password = (string) $request->request->get($passwordField, '');

        if ($username === '' || strlen($username) > UserBadge::MAX_USERNAME_LENGTH) {
            throw new BadCredentialsException('Invalid username.');
        }

        return [$username, $password];
    }

    public function start(Request $request, ?AuthenticationException $authException = null): RedirectResponse
    {
        return new RedirectResponse(
            $this->urlGenerator->generate('game.login'),
            Response::HTTP_TEMPORARY_REDIRECT
        );
    }
}
