<?PHP

	//////////////////////////////////////////////////
	//		 	 ____    __           ______       			//
	//			/\  _`\ /\ \__       /\  _  \      			//
	//			\ \ \L\_\ \ ,_\   ___\ \ \L\ \     			//
	//			 \ \  _\L\ \ \/  / __`\ \  __ \    			//
	//			  \ \ \L\ \ \ \_/\ \L\ \ \ \/\ \   			//
	//	  		 \ \____/\ \__\ \____/\ \_\ \_\  			//
	//			    \/___/  \/__/\/___/  \/_/\/_/  	 		//
	//																					 		//
	//////////////////////////////////////////////////
	// The Andromeda-Project-Browsergame				 		//
	// Ein Massive-Multiplayer-Online-Spiel			 		//
	// Programmiert von Nicolas Perrenoud				 		//
	// www.nicu.ch | mail@nicu.ch								 		//
	// als Maturaarbeit '04 am Gymnasium Oberaargau	//
	//////////////////////////////////////////////////	
	//
	// 	Dateiname: events.php	
	// 	Topic: Formular-Definitionen für Events 
	// 	Autor: Nicolas Perrenoud alias MrCage							
	// 	Erstellt: 26.04.2006
	// 	Bearbeitet von: Nicolas Perrenoud alias MrCage
	// 	Bearbeitet am: 26.04.2006
	// 	Kommentar: 	
	//
	
	// VARIABLES
	
	define(MODUL_NAME,"Ereignisse");				
	define(DB_TABLE, $db_table['events']);
	define("DB_TABLE_ID", "event_id");
	define("DB_OVERVIEW_ORDER_FIELD","event_title");
	
	// FIELDS
	
	// Description:
	
	// name	 											// DB Field Name
	// text												// Field Description
	// type												// Field Type: text, password, textarea, timestamp, radio, select, checkbox, email, url, numeric
	// def_val										// Default Value
	// size 											// Field length (text, password, date, email, url)
	// maxlen 										// Max Text length (text, password, date, email, url)
	// rows 											// Rows (textarea)
	// cols												// Cols (textarea)
	// rcb_elem (Array)						// Checkbox-/Radio Elements (desc=>value)
	// rcb_elem_chekced						// Value of default checked Checkbox-/Radio Element (Checkbox: has to be an array)
	// select_elem (Array)				// Select Elements (desc=>value)
	// select_elem_checked				// Value of default checked Select Element (desc=>value)
	// show_overview							// Set 1 to show on overview page
  
	$db_fields = array ( 0	=> 	array	(	"name" => "event_title",
																		"text" => "Titel",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 1
																	),
											1	=> 	array	(	"name" => "event_text",
																		"text" => "Text",
																		"type" => "textarea",
																		"def_val" => "",
																		"size" => "",
																		"maxlen" => "",
																		"rows" => "5",
																		"cols" => "30",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											2	=> 	array	(	"name" => "event_ask",
																		"text" => "Antwort erwartet",
																		"type" => "radio",
																		"def_val" => "",
																		"size" => "",
																		"maxlen" => "",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => array("Ja"=>1,"Nein"=>0),
																		"rcb_elem_chekced" => "0",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											3	=> 	array	(	"name" => "event_answer_pos",
																		"text" => "Antwort positiv",
																		"type" => "textarea",
																		"def_val" => "",
																		"size" => "",
																		"maxlen" => "",
																		"rows" => "5",
																		"cols" => "30",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											4	=> 	array	(	"name" => "event_answer_neg",
																		"text" => "Antwort negativ",
																		"type" => "textarea",
																		"def_val" => "",
																		"size" => "",
																		"maxlen" => "",
																		"rows" => "5",
																		"cols" => "30",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),		
											5	=> 	array	(	"name" => "event_execrate",
																		"text" => "Ausführungswahrscheinlichkeit)",
																		"type" => "text",
																		"def_val" => "100",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 1
																	),		

// Belohnung positive Antwort			
																																
											6	=> 	array	(	"name" => "event_reward_p_rate",
																		"text" => "Positiv: Faktor Belohnung",
																		"type" => "text",
																		"def_val" => "0.01",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											7	=> 	array	(	"name" => "event_reward_p_metal_min",
																		"text" => "Positiv: Belohnung Metall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											8	=> 	array	(	"name" => "event_reward_p_metal_max",
																		"text" => "Positiv: Belohnung Metall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											9	=> 	array	(	"name" => "event_reward_p_crystal_min",
																		"text" => "Positiv: Belohnung Kristall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											10	=> 	array	(	"name" => "event_reward_p_crystal_max",
																		"text" => "Positiv: Belohnung Kristall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											11	=> 	array	(	"name" => "event_reward_p_plastic_min",
																		"text" => "Positiv: Belohnung Plastik Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											12	=> 	array	(	"name" => "event_reward_p_plastic_max",
																		"text" => "Positiv: Belohnung Plastik Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											13	=> 	array	(	"name" => "event_reward_p_fuel_min",
																		"text" => "Positiv: Belohnung Treibstoff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											14	=> 	array	(	"name" => "event_reward_p_fuel_max",
																		"text" => "Positiv: Belohnung Treibstoff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											15	=> 	array	(	"name" => "event_reward_p_food_min",
																		"text" => "Positiv: Belohnung Nahrung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											16	=> 	array	(	"name" => "event_reward_p_food_max",
																		"text" => "Positiv: Belohnung Nahrung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											17	=> 	array	(	"name" => "event_reward_p_people_min",
																		"text" => "Positiv: Belohnung Personen Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											18	=> 	array	(	"name" => "event_reward_p_people_max",
																		"text" => "Positiv: Belohnung Personen Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),

											19	=> 	array	(	"name" => "event_reward_p_ship_id",
																		"text" => "Positiv: Belohnung Schiff",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['ships'],"ship_id","ship_name","ship_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											20	=> 	array	(	"name" => "event_reward_p_ship_min",
																		"text" => "Positiv: Belohnung Schiff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											21	=> 	array	(	"name" => "event_reward_p_ship_max",
																		"text" => "Positiv: Belohnung Schiff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										22	=> 	array	(	"name" => "event_reward_p_def_id",
																		"text" => "Positiv: Belohnung Verteidigung",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['defense'],"def_id","def_name","def_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											23	=> 	array	(	"name" => "event_reward_p_def_min",
																		"text" => "Positiv: Belohnung Verteidigung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											24	=> 	array	(	"name" => "event_reward_p_def_max",
																		"text" => "Positiv: Belohnung Verteidigung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										25	=> 	array	(	"name" => "event_reward_p_building_id",
																		"text" => "Positiv: Belohnung Gebäude",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['buildings'],"building_id","building_name","building_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											26	=> 	array	(	"name" => "event_reward_p_building_level",
																		"text" => "Positiv: Belohnung Gebäude Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										27	=> 	array	(	"name" => "event_reward_p_tech_id",
																		"text" => "Positiv: Belohnung Technologie",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['technologies'],"tech_id","tech_name","tech_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											28	=> 	array	(	"name" => "event_reward_p_tech_level",
																		"text" => "Positiv: Belohnung Technologie Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
// Kosten positive Antwort

											29	=> 	array	(	"name" => "event_costs_p_rate",
																		"text" => "Positiv: Faktor Kosten",
																		"type" => "text",
																		"def_val" => "0.01",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											30	=> 	array	(	"name" => "event_costs_p_metal_min",
																		"text" => "Positiv: Kosten Metall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											31	=> 	array	(	"name" => "event_costs_p_metal_max",
																		"text" => "Positiv: Kosten Metall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											32	=> 	array	(	"name" => "event_costs_p_crystal_min",
																		"text" => "Positiv: Kosten Kristall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											33	=> 	array	(	"name" => "event_costs_p_crystal_max",
																		"text" => "Positiv: Kosten Kristall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											34	=> 	array	(	"name" => "event_costs_p_plastic_min",
																		"text" => "Positiv: Kosten Plastik Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											35	=> 	array	(	"name" => "event_costs_p_plastic_max",
																		"text" => "Positiv: Kosten Plastik Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											36	=> 	array	(	"name" => "event_costs_p_fuel_min",
																		"text" => "Positiv: Kosten Treibstoff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											37	=> 	array	(	"name" => "event_costs_p_fuel_max",
																		"text" => "Positiv: Kosten Treibstoff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											38	=> 	array	(	"name" => "event_costs_p_food_min",
																		"text" => "Positiv: Kosten Nahrung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											39	=> 	array	(	"name" => "event_costs_p_food_max",
																		"text" => "Positiv: Kosten Nahrung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											40	=> 	array	(	"name" => "event_costs_p_people_min",
																		"text" => "Positiv: Kosten Personen Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											41	=> 	array	(	"name" => "event_costs_p_people_max",
																		"text" => "Positiv: Kosten Personen Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),

											42	=> 	array	(	"name" => "event_costs_p_ship_id",
																		"text" => "Positiv: Kosten Schiff",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['ships'],"ship_id","ship_name","ship_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											43	=> 	array	(	"name" => "event_costs_p_ship_min",
																		"text" => "Positiv: Kosten Schiff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											44	=> 	array	(	"name" => "event_costs_p_ship_max",
																		"text" => "Positiv: Kosten Schiff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										45	=> 	array	(	"name" => "event_costs_p_def_id",
																		"text" => "Positiv: Kosten Verteidigung",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['defense'],"def_id","def_name","def_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											46	=> 	array	(	"name" => "event_costs_p_def_min",
																		"text" => "Positiv: Kosten Verteidigung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											47	=> 	array	(	"name" => "event_costs_p_def_max",
																		"text" => "Positiv: Kosten Verteidigung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										48	=> 	array	(	"name" => "event_costs_p_building_id",
																		"text" => "Positiv: Kosten Gebäude",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['buildings'],"building_id","building_name","building_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											49	=> 	array	(	"name" => "event_costs_p_building_level",
																		"text" => "Positiv: Kosten Gebäude Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										50	=> 	array	(	"name" => "event_costs_p_tech_id",
																		"text" => "Positiv: Kosten Technologie",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['technologies'],"tech_id","tech_name","tech_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											51	=> 	array	(	"name" => "event_costs_p_tech_level",
																		"text" => "Positiv: Kosten Technologie Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),


//
//

// Belohnung negative Antwort			
																																
											52	=> 	array	(	"name" => "event_reward_n_rate",
																		"text" => "Negativ: Faktor Belohnung",
																		"type" => "text",
																		"def_val" => "0.01",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											53	=> 	array	(	"name" => "event_reward_n_metal_min",
																		"text" => "Negativ: Belohnung Metall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											54	=> 	array	(	"name" => "event_reward_n_metal_max",
																		"text" => "Negativ: Belohnung Metall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											55	=> 	array	(	"name" => "event_reward_n_crystal_min",
																		"text" => "Negativ: Belohnung Kristall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											56	=> 	array	(	"name" => "event_reward_n_crystal_max",
																		"text" => "Negativ: Belohnung Kristall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											57	=> 	array	(	"name" => "event_reward_n_plastic_min",
																		"text" => "Negativ: Belohnung Plastik Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											58	=> 	array	(	"name" => "event_reward_n_plastic_max",
																		"text" => "Negativ: Belohnung Plastik Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											59	=> 	array	(	"name" => "event_reward_n_fuel_min",
																		"text" => "Negativ: Belohnung Treibstoff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											60	=> 	array	(	"name" => "event_reward_n_fuel_max",
																		"text" => "Negativ: Belohnung Treibstoff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											61	=> 	array	(	"name" => "event_reward_n_food_min",
																		"text" => "Negativ: Belohnung Nahrung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											62	=> 	array	(	"name" => "event_reward_n_food_max",
																		"text" => "Negativ: Belohnung Nahrung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											63	=> 	array	(	"name" => "event_reward_n_people_min",
																		"text" => "Negativ: Belohnung Personen Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											64	=> 	array	(	"name" => "event_reward_n_people_max",
																		"text" => "Negativ: Belohnung Personen Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),

											65	=> 	array	(	"name" => "event_reward_n_ship_id",
																		"text" => "Negativ: Belohnung Schiff",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['ships'],"ship_id","ship_name","ship_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											66	=> 	array	(	"name" => "event_reward_n_ship_min",
																		"text" => "Negativ: Belohnung Schiff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											67	=> 	array	(	"name" => "event_reward_n_ship_max",
																		"text" => "Negativ: Belohnung Schiff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										68	=> 	array	(	"name" => "event_reward_n_def_id",
																		"text" => "Negativ: Belohnung Verteidigung",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['defense'],"def_id","def_name","def_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											69	=> 	array	(	"name" => "event_reward_n_def_min",
																		"text" => "Negativ: Belohnung Verteidigung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											70	=> 	array	(	"name" => "event_reward_n_def_max",
																		"text" => "Negativ: Belohnung Verteidigung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										71	=> 	array	(	"name" => "event_reward_n_building_id",
																		"text" => "Negativ: Belohnung Gebäude",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['buildings'],"building_id","building_name","building_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											72	=> 	array	(	"name" => "event_reward_n_building_level",
																		"text" => "Negativ: Belohnung Gebäude Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										73	=> 	array	(	"name" => "event_reward_n_tech_id",
																		"text" => "Negativ: Belohnung Technologie",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['technologies'],"tech_id","tech_name","tech_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											74	=> 	array	(	"name" => "event_reward_n_tech_level",
																		"text" => "Negativ: Belohnung Technologie Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
																

// Kosten negative Antwort

											75	=> 	array	(	"name" => "event_costs_n_rate",
																		"text" => "Negativ: Faktor Kosten",
																		"type" => "text",
																		"def_val" => "0.01",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											76	=> 	array	(	"name" => "event_costs_n_metal_min",
																		"text" => "Negativ: Kosten Metall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											77	=> 	array	(	"name" => "event_costs_n_metal_max",
																		"text" => "Negativ: Kosten Metall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											78	=> 	array	(	"name" => "event_costs_n_crystal_min",
																		"text" => "Negativ: Kosten Kristall Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											79	=> 	array	(	"name" => "event_costs_n_crystal_max",
																		"text" => "Negativ: Kosten Kristall Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											80	=> 	array	(	"name" => "event_costs_n_plastic_min",
																		"text" => "Negativ: Kosten Plastik Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											81	=> 	array	(	"name" => "event_costs_n_plastic_max",
																		"text" => "Negativ: Kosten Plastik Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											82	=> 	array	(	"name" => "event_costs_n_fuel_min",
																		"text" => "Negativ: Kosten Treibstoff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											83	=> 	array	(	"name" => "event_costs_n_fuel_max",
																		"text" => "Negativ: Kosten Treibstoff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											84	=> 	array	(	"name" => "event_costs_n_food_min",
																		"text" => "Negativ: Kosten Nahrung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											85	=> 	array	(	"name" => "event_costs_n_food_max",
																		"text" => "Negativ: Kosten Nahrung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											86	=> 	array	(	"name" => "event_costs_n_people_min",
																		"text" => "Negativ: Kosten Personen Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),
											87	=> 	array	(	"name" => "event_costs_n_people_max",
																		"text" => "Negativ: Kosten Personen Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),

											88	=> 	array	(	"name" => "event_costs_n_ship_id",
																		"text" => "Negativ: Kosten Schiff",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['ships'],"ship_id","ship_name","ship_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											89	=> 	array	(	"name" => "event_costs_n_ship_min",
																		"text" => "Negativ: Kosten Schiff Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											90	=> 	array	(	"name" => "event_costs_n_ship_max",
																		"text" => "Negativ: Kosten Schiff Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										91	=> 	array	(	"name" => "event_costs_n_def_id",
																		"text" => "Negativ: Kosten Verteidigung",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['defense'],"def_id","def_name","def_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											92	=> 	array	(	"name" => "event_costs_n_def_min",
																		"text" => "Negativ: Kosten Verteidigung Min",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),																	
											93	=> 	array	(	"name" => "event_costs_n_def_max",
																		"text" => "Negativ: Kosten Verteidigung Max",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										94	=> 	array	(	"name" => "event_costs_n_building_id",
																		"text" => "Negativ: Kosten Gebäude",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['buildings'],"building_id","building_name","building_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											95	=> 	array	(	"name" => "event_costs_n_building_level",
																		"text" => "Negativ: Kosten Gebäude Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),	
										96	=> 	array	(	"name" => "event_costs_n_tech_id",
																		"text" => "Negativ: Kosten Technologie",
																		"type" => "select",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => admin_get_select_elements($db_table['technologies'],"tech_id","tech_name","tech_name",array("0"=>"(Keins)")),
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	),				
											97	=> 	array	(	"name" => "event_costs_n_tech_level",
																		"text" => "Negativ: Kosten Technologie Stufenanstieg",
																		"type" => "text",
																		"def_val" => "",
																		"size" => "20",
																		"maxlen" => "250",
																		"rows" => "",
																		"cols" => "",
																		"rcb_elem" => "",
																		"rcb_elem_chekced" => "",
																		"select_elem" => "",
																		"select_elem_checked" => "",
																		"show_overview" => 0
																	)																	


											);
        
?>