FIND_PATH(MYSQLPP_INCLUDE_DIR mysql++.h /usr/include/mysql++ /usr/local/include/mysql++)

FIND_LIBRARY(MYSQLPP_LIBRARY NAMES mysqlpp PATH /usr/lib /usr/local/lib)

FIND_LIBRARY(MYSQLCLIENT_LIBRARY NAMES mysqlclient PATH /usr/local/lib)

IF (MYSQLPP_INCLUDE_DIR AND MYSQLPP_LIBRARY)
   SET(MYSQLPP_FOUND TRUE)
ENDIF (MYSQLPP_INCLUDE_DIR AND MYSQLPP_LIBRARY)

IF (MYSQLCLIENT_LIBRARY)
      MESSAGE(STATUS "Found MySQL Client: ${MYSQLCLIENT_LIBRARY}")
ENDIF (MYSQLCLIENT_LIBRARY)


IF (MYSQLPP_FOUND)
   IF (NOT Foo_FIND_QUIETLY)
      MESSAGE(STATUS "Found MySQL++: ${MYSQLPP_LIBRARY}")
   ENDIF (NOT Foo_FIND_QUIETLY)
ELSE (MYSQLPP_FOUND)
   IF (Foo_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find MySQL++")
   ENDIF (Foo_FIND_REQUIRED)
ENDIF (MYSQLPP_FOUND)
