name: GUI CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.0"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1, phar.readonly=0"
          php-version: "${{ matrix.php-version }}"

      - name: Composer Cache Directory
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ~/.composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up Symfony DB config
        run: echo 'DATABASE_URL="mysql://root:root@127.0.0.1:${{ job.services.mysql.ports[3306] }}/etoa?serverVersion=5.7"' > .env.test

      - name: Validate composer.json and composer.lock
        run: ./composer.phar validate

      - name: Install dependencies
        run: ./composer.phar install --prefer-dist --no-progress --no-suggest

      - name: Create DB
        run: ./bin/console doctrine:database:create --env=test

      - name: Set up DB
        run: bin/console database:migrate --env=test

      - name: Set up DB config
        run: echo '{"host":"127.0.0.1:${{ job.services.mysql.ports[3306] }}","dbname":"etoa","user":"root","password":"root"}' > htdocs/config/db.conf

      - name: "Client dummy files"
        run: |
          mkdir -p ./htdocs/web/build
          echo "{}" > ./htdocs/web/build/manifest.json
          echo '{"entrypoints": {"admin": {}}}' > ./htdocs/web/build/entrypoints.json

      - name: PHPUnit
        run: ./vendor/bin/phpunit tests

  php-cs-fixer-src:
    strategy:
      matrix:
        php-version:
          - "8.0"

    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1, phar.readonly=0"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-phpcsfixer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-phpcsfixer"

      - name: Install dependencies
        run: ./composer.phar install --prefer-dist --no-progress --no-suggest

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

  phpstan:
    strategy:
      matrix:
        php-version:
          - "8.0"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1, phar.readonly=0"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-phpstan-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-phpstan"

      - name: Set up Symfony DB config
        run: echo 'DATABASE_URL="mysql://root:root@127.0.0.1:${{ job.services.mysql.ports[3306] }}/etoa?serverVersion=5.7"' > .env.test

      - name: Install dependencies
        run: ./composer.phar install --prefer-dist --no-progress --no-suggest

      - name: Set up DB config
        run: echo '{"host":"127.0.0.1:${{ job.services.mysql.ports[3306] }}","dbname":"etoa_test","user":"root","password":"root"}' > htdocs/config/db.conf

      - name: Setup container
        run: ./bin/console debug:container --quiet

      - name: Create DB
        run: ./bin/console doctrine:database:create --env=test

      - name: Set up DB
        run: bin/console database:migrate --env=test

      - name: Set up Symfony DB config
        run: echo 'DATABASE_URL="mysql://root:root@127.0.0.1:${{ job.services.mysql.ports[3306] }}/etoa_test?serverVersion=5.7"' > .env.test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress
        env:
          APP_ENV: test

  frontend-assets:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: ./composer.phar install --prefer-dist --no-progress --no-suggest --no-plugins --no-dev --ignore-platform-reqs

      - run: yarn install --frozen-lockfile
      - run: yarn run prod-mix
      - run: yarn run build
